version: '3.8'

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_OPEN_WEATHER_API_KEY: ${NEXT_PUBLIC_OPEN_WEATHER_API_KEY}
        NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_OPEN_WEATHER_API_KEY=${NEXT_PUBLIC_OPEN_WEATHER_API_KEY}
      - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    restart: unless-stopped
    container_name: nextjs-weather-app
